//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUTH_RCTPL.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.isap.com/", ConfigurationName="ServiceReference1.COCRegistration")]
    public interface COCRegistration {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AUTH_RCTPL.ServiceReference1.registerResponse register(AUTH_RCTPL.ServiceReference1.register request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AUTH_RCTPL.ServiceReference1.registerResponse> registerAsync(AUTH_RCTPL.ServiceReference1.register request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.isap.com/")]
    public partial class registration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string assuredNameField;
        
        private string assuredTinField;
        
        private string authNoField;
        
        private string chassisNoField;
        
        private string cocNoField;
        
        private string engineNoField;
        
        private string errorMessageField;
        
        private string expiryDateField;
        
        private string inceptionDateField;
        
        private string mvFileNoField;
        
        private string mvPremTypeField;
        
        private string mvTypeField;
        
        private string passwordField;
        
        private string plateNoField;
        
        private string premiumTypeField;
        
        private string regTypeField;
        
        private string successMessageField;
        
        private string taxTypeField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string assuredName {
            get {
                return this.assuredNameField;
            }
            set {
                this.assuredNameField = value;
                this.RaisePropertyChanged("assuredName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string assuredTin {
            get {
                return this.assuredTinField;
            }
            set {
                this.assuredTinField = value;
                this.RaisePropertyChanged("assuredTin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string authNo {
            get {
                return this.authNoField;
            }
            set {
                this.authNoField = value;
                this.RaisePropertyChanged("authNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string chassisNo {
            get {
                return this.chassisNoField;
            }
            set {
                this.chassisNoField = value;
                this.RaisePropertyChanged("chassisNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cocNo {
            get {
                return this.cocNoField;
            }
            set {
                this.cocNoField = value;
                this.RaisePropertyChanged("cocNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string engineNo {
            get {
                return this.engineNoField;
            }
            set {
                this.engineNoField = value;
                this.RaisePropertyChanged("engineNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string inceptionDate {
            get {
                return this.inceptionDateField;
            }
            set {
                this.inceptionDateField = value;
                this.RaisePropertyChanged("inceptionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string mvFileNo {
            get {
                return this.mvFileNoField;
            }
            set {
                this.mvFileNoField = value;
                this.RaisePropertyChanged("mvFileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string mvPremType {
            get {
                return this.mvPremTypeField;
            }
            set {
                this.mvPremTypeField = value;
                this.RaisePropertyChanged("mvPremType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string mvType {
            get {
                return this.mvTypeField;
            }
            set {
                this.mvTypeField = value;
                this.RaisePropertyChanged("mvType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string plateNo {
            get {
                return this.plateNoField;
            }
            set {
                this.plateNoField = value;
                this.RaisePropertyChanged("plateNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string premiumType {
            get {
                return this.premiumTypeField;
            }
            set {
                this.premiumTypeField = value;
                this.RaisePropertyChanged("premiumType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string regType {
            get {
                return this.regTypeField;
            }
            set {
                this.regTypeField = value;
                this.RaisePropertyChanged("regType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string successMessage {
            get {
                return this.successMessageField;
            }
            set {
                this.successMessageField = value;
                this.RaisePropertyChanged("successMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string taxType {
            get {
                return this.taxTypeField;
            }
            set {
                this.taxTypeField = value;
                this.RaisePropertyChanged("taxType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="register", WrapperNamespace="http://api.isap.com/", IsWrapped=true)]
    public partial class register {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.isap.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AUTH_RCTPL.ServiceReference1.registration arg0;
        
        public register() {
        }
        
        public register(AUTH_RCTPL.ServiceReference1.registration arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerResponse", WrapperNamespace="http://api.isap.com/", IsWrapped=true)]
    public partial class registerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.isap.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AUTH_RCTPL.ServiceReference1.registration @return;
        
        public registerResponse() {
        }
        
        public registerResponse(AUTH_RCTPL.ServiceReference1.registration @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface COCRegistrationChannel : AUTH_RCTPL.ServiceReference1.COCRegistration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class COCRegistrationClient : System.ServiceModel.ClientBase<AUTH_RCTPL.ServiceReference1.COCRegistration>, AUTH_RCTPL.ServiceReference1.COCRegistration {
        
        public COCRegistrationClient() {
        }
        
        public COCRegistrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public COCRegistrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public COCRegistrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public COCRegistrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AUTH_RCTPL.ServiceReference1.registerResponse AUTH_RCTPL.ServiceReference1.COCRegistration.register(AUTH_RCTPL.ServiceReference1.register request) {
            return base.Channel.register(request);
        }
        
        public AUTH_RCTPL.ServiceReference1.registration register(AUTH_RCTPL.ServiceReference1.registration arg0) {
            AUTH_RCTPL.ServiceReference1.register inValue = new AUTH_RCTPL.ServiceReference1.register();
            inValue.arg0 = arg0;
            AUTH_RCTPL.ServiceReference1.registerResponse retVal = ((AUTH_RCTPL.ServiceReference1.COCRegistration)(this)).register(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AUTH_RCTPL.ServiceReference1.registerResponse> AUTH_RCTPL.ServiceReference1.COCRegistration.registerAsync(AUTH_RCTPL.ServiceReference1.register request) {
            return base.Channel.registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<AUTH_RCTPL.ServiceReference1.registerResponse> registerAsync(AUTH_RCTPL.ServiceReference1.registration arg0) {
            AUTH_RCTPL.ServiceReference1.register inValue = new AUTH_RCTPL.ServiceReference1.register();
            inValue.arg0 = arg0;
            return ((AUTH_RCTPL.ServiceReference1.COCRegistration)(this)).registerAsync(inValue);
        }
    }
}
